#
# This file contains configuration flags to customize your site
#
safe: true
highlighter: pygments
lsi: false


# Name of your site (displayed in the header)
name: cloudshand

# Short bio or description (displayed in the header)
description: 구름손여행기 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: #https://avatars2.githubusercontent.com/u/5708556?v=3&s=460

#
# Flags below are optional
#

# Pagination : how many pages you want to be shown 

paginate: 3

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: clouds2
  instagram: 
  linkedin: 
  pinterest: 
  rss: rss
  twitter: cloudshand
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"

# Your disqus shortname, entering this will enable commenting on posts
disqus: clouds2

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: #UA-3025669-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://clouds2.github.io #http://seoulrain.net

production_url : http://clouds2.github.io
rss_path : /rss.xml

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet

redcarpet:
  extensions: 
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap



permalink: pretty 
# permalink: /:categories/:year/:month/:day/:title

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
